## Hands on!

In [1]:
import sys
import numpy as np

## Basic numpy

In [5]:
a = np.array([1,2,3,8,6,7])

## Array Types

In [7]:
a.dtype

dtype('int32')

In [15]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

## Dimensions, shapes, indexing and slice

In [16]:
A = np.array([
    [1,2,3],
    [5,1,9]
])

In [18]:
A.shape

(2, 3)

In [19]:
A.ndim

2

In [20]:
A.size

6

In [21]:
# A[0][1] == A[0,1]

In [22]:
A[:, :2]

array([[1, 2],
       [5, 1]])

## Statistics

In [24]:
a = np.array([
    [1,2,3],
    [5,1,9],
    [2,5,7]
])

In [ ]:
a.sum()

In [ ]:
a.mean()

In [ ]:
a.std()

In [ ]:
a.var()

In [25]:
a.sum(axis=0) # sum of column

array([ 8,  8, 19])

In [26]:
a.sum(axis=1) # sum of row

array([ 6, 15, 14])

In [ ]:
# mean , std, var has axis parameter as sum

## Broadcasting and vertorized operations:

In [29]:
a = np.arange(4)

In [31]:
a

array([0, 1, 2, 3])

In [32]:
a + 10 # because array in numpy is immutable, so a + 10 will create new array. We can use += to override original array

array([10, 11, 12, 13])

## Boolean Array

In [37]:
a = np.array([3, 1, 5, 7, 2, 0, 6])

In [38]:
a[a>3]

array([5, 7, 6])

In [39]:
a[a > a.mean()]

array([5, 7, 6])

In [42]:
a[ (a == 0) | (a == 4)]

array([0])

In [43]:
a > 2

array([ True, False,  True,  True, False, False,  True])

## Linear Algebra

In [45]:
a = np.array([
    [1,2,3],
    [5,1,9],
    [2,5,7]
])

In [46]:
b = np.array([
    [3,1],
    [2,8],
    [7,3]
])

In [49]:
a.dot(b)

array([[28, 26],
       [80, 40],
       [65, 63]])

In [50]:
a @ b

array([[28, 26],
       [80, 40],
       [65, 63]])

In [52]:
b.T

array([[3, 2, 7],
       [1, 8, 3]])

In [53]:
b.T @ a

array([[27, 43, 76],
       [47, 25, 96]])